services:
  postgres:
    image: postgres:16
    container_name: letstriptogether-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lets-trip-together
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack-server:7.2.0-v19
    container_name: letstriptogether-redis
    environment:
      REDIS_ARGS: "--requirepass admin"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  letstriptogether-internal-api:
    profiles:
      - api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: letstriptogether-internal-api
    ports:
      - "5088:5088"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=lets-trip-together;Username=admin;Password=${POSTGRES_PASSWORD:-root}
      - ConnectionStrings__Redis=redis:6379,password=${REDIS_PASSWORD:-admin}
      - JsonWebTokenSettings__SecretKey=${JWT_SECRET_KEY:-your_jwt_secret_key}
      - EmailSettings__SmtpServer=${SMTP_SERVER:-sandbox.smtp.mailtrap.io}
      - EmailSettings__Username=${SMTP_USERNAME:-your_smtp_username}
      - EmailSettings__Password=${SMTP_PASSWORD:-your_smtp_password}
    networks:
      - postgres_network
      - redis_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:

networks:
  postgres_network:
  redis_network:
